--ALTER TABLE USERS DROP PRIMARY KEY, add PRIMARY KEY(ID, NAME) ;

--ALTER TABLE USERS 
--	MODIFY ID INT NOT NULL;
--DROP PRIMARY KEY;


--ALTER TABLE USERS 
--ADD CONSTRAINT ID PRIMARY KEY (ID,USERNAME);

--ALTER TABLE users
--DROP id PRIMARY KEY,
--ADD `id` CONSTRAINT pk_users PRIMARY KEY (`id`, `username`);


ALTER TABLE users
  DROP CONSTRAINT USERS_ID;
ALTER TABLE users
  ADD CONSTRAINT pk_users PRIMARY KEY (id,username);