CREATE FUNCTION 
ufn_CalculateFutureValue(@SUMa DECIMAL(15,2), @RATE float,@YEARS INT)
RETURNS DECIMAL(15,4)
BEGIN
	DECLARE @RESULT DECIMAL(15,4)
	SET @RESULT=POWER((1+@RATE),@YEARS)*@SUMa
	RETURN @RESULT
END

select dbo.ufn_CalculateFutureValue(1000,0.1, 5)