CREATE FUNCTION ufn_GetSalaryLevel(@salary DECIMAL(18,4)) 
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @RESULT VARCHAR(15)
	IF (@SALARY<30000) SET @RESULT='Low'
	ELSE IF (@salary BETWEEN 30000 AND 50000) SET @RESULT='Average'
	ELSE SET @RESULT='High' 
RETURN @RESULT
END 

SELECT FirstName,LastName, Salary, DBO.ufn_GetSalaryLevel(SALARY)
FROM Employees