CREATE function udf_GetCost(@JobId int)
RETURNS decimal(15,2)

BEGIN
	DECLARE @RESULT DECIMAL(15,2)=( SELECT SUM([PRICE TOTAL]) FROM
	(	SELECT O.JOBID,O.OrderId, OP.QUANTITY, P.PRICE, OP.QUANTITY* P.PRICE AS[PRICE TOTAL]  
		FROM ORDERS  AS O
		JOIN OrderParts AS OP ON OP.OrderId=O.OrderId
		JOIN PARTS AS P ON OP.PartId=P.PartId
		WHERE JobId=@JobId) AS RES
	GROUP BY JobId)
	IF (@RESULT IS NULL)
		SET @RESULT =0
	RETURN @RESULT	
END

SELECT dbo.udf_GetCost(2)

